### ISSUE TITLE
FetchAccountInfo function is returning none for some reason

### ISSUE THREAD

**Issue by Mohammad-Hamzah** [infrared-o8/python-sql-project-1#2]
![image](https://github.com/user-attachments/assets/39ff4561-fec2-43d5-a68d-cde9c439b4a7)

**Comment by infrared-o8** [comment]
![image](https://github.com/user-attachments/assets/f0b6de81-489d-4d5d-b786-07af45baa207)
here, the null value comes because we were not able to fetch the account info... sending the log.txt file would be helpful too, it should be at C:/Users/moham/HospitalManagement-PythonSQL/

**Comment by infrared-o8** [comment]
i suggest to try logging in as an admin, use adm1 and 'adminboi' as the password, and display the patients table, search if your new account is in there. let me know of the results.

**Comment by Mohammad-Hamzah** [comment]
> i suggest to try logging in as an admin, use adm1 and 'adminboi' as the password, and display the patients table, search if your new account is in there. let me know of the results.

yea but this issue arises just after creating the database

**Comment by infrared-o8** [comment]
have u tried deleting the creds.dat file at C:/Users/moham/HospitalManagement-PythonSQL?
