### ISSUE TITLE
Forest theme for pretty table throws an error

### ISSUE THREAD

**Issue by Mohammad-Hamzah** [infrared-o8/python-sql-project-1#3]
![image](https://github.com/user-attachments/assets/bd218ccd-b853-41a5-96b0-eb96ab81d6d7)
###Forest theme throwing an error

**Comment by infrared-o8** [comment]
i had manually edited the colortable module locally, to add themes. I'll remove this feature. thanks!

**Comment by Mohammad-Hamzah** [comment]
welcome :) ❤️
